### ISSUE TITLE
publish to npm?

### ISSUE THREAD

**Issue by jcesarmobile** [sampart/cordova-plugin-app-version#116]
0.1.10 appears as the latest release on github, but on npm 0.1.9 is still latest.
So not sure if the 0.1.10 on github is a mistake or if you forgot to publish it to npm

**Comment by Gillardo** [comment]
agreed, can this be published please

**Comment by sampart** [comment]
Hi both, thanks for commenting. It's worth noting that this plugin [isn't actively mantained](https://github.com/whiteoctober/cordova-plugin-app-version/issues/100) but I agree it would be good to get the latest release on npm nonetheless.  Of course, if someone else does pick this up with a fork (see linked issue) that could be their first release under the new scope.

I've not worked on this project (I just have permissions on the repo), and don't know the account that was used to publish this to npm.  I know that @richsage, @rjmunro, @Drarok and @AWildDevAppears have worked on this in the past, so I'm tagging them to see if they can help.  Their involvement was a long time ago, though, so no promises!

**Comment by richsage** [comment]
Yeah think it was @rjmunro originally - definitely not me as I have no account on the registry :)

**Comment by jcesarmobile** [comment]
0.1.12 is now published on npm, so closing my issue

BTW, latest on github is 0.1.11

**Comment by sampart** [comment]
Ooh, good spot. Thanks, @jcesarmobile. I've created a 0.1.12 release on GitHub too now: https://github.com/sampart/cordova-plugin-app-version/releases/tag/0.1.12
