### ISSUE TITLE
Small error in browser version

### ISSUE THREAD

**Issue by piwel** [sampart/cordova-plugin-app-version#118]
Hi WhiteOctober,

There's a small typo in here: 
https://github.com/whiteoctober/cordova-plugin-app-version/blob/a5ae663116f7028a9bd7e83f5aa9f47beee815df/src/browser/AppVersionProxy.js#L27-L29

`e is not defined`, indeed, could you please remove it, or add it in the function call parameters on the line just above?

Thanks by advance

**Comment by sampart** [comment]
Fixed in https://github.com/sampart/cordova-plugin-app-version/pull/129 ❤️
