### ISSUE TITLE
Browser version failing to find config.xml

### ISSUE THREAD

**Issue by Djones4822** [sampart/cordova-plugin-app-version#128]
Cordova version 11.0.0

**Issue**: Using the browser build, the xhr request fails to locate the file `config.xml` 

I think this is because the xhr request to `../config.xml` is searching the parent of the root - I think this would be solved by just using `config.xml` . 

This is based on my understanding of the directory structure: https://cordova.apache.org/docs/en/11.x/reference/cordova-cli/index.html#directory-structure

Is there a specific reason that `../config.xml` is used that I'm not aware of?

Also, I'm aware that the repo is unmaintained, I'm hoping there's anyone who objects to my proposed fix, I will submit the PR if not.

**Comment by sampart** [comment]
Fixed in #129 ❤️
